Optimize existing and prepare for possible deps
Pronovix/devportal-starterkit pull request #29
Opened 2019-06-12 17:19 UTC by boobaa

2019-06-12 17:22 UTC, tamasd approved these changes

2019-06-13 06:04 UTC, merged

2019-06-13 07:04 UTC, mxr576 requested changes

2019-06-13 07:04 UTC, mxr576 commented on composer.json
> +        "oomphinc/composer-installers-extender": "^1.1"
Sort these alphabetically :)

2019-06-13 07:10 UTC, boobaa commented on composer.json
> +        "oomphinc/composer-installers-extender": "^1.1"
Next time. Thanks! :)